Class {
	#name : #MRDBMSBoolean,
	#superclass : #Object,
	#category : #'MiniRDBMS-Basic'
}

{ #category : #'logical operations' }
MRDBMSBoolean >> & aRDBMSBoolean [
	^ self subclassResponsibility
]

{ #category : #'logical operations' }
MRDBMSBoolean >> not [
	^ self subclassResponsibility
]

{ #category : #'logical operations' }
MRDBMSBoolean >> | aRDBMSBoolean [
	^ self subclassResponsibility
]
